# Generated by Django 3.0.2 on 2020-01-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='editor_html',
            field=models.TextField(default='', verbose_name='html generated by editor'),
        ),
    ]
