# Generated by Django 3.0.2 on 2020-01-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_lesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.CharField(default='sluggy', max_length=300),
            preserve_default=False,
        ),
    ]
