# Generated by Django 3.0.2 on 2020-01-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0005_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='editor_html',
            field=models.TextField(blank=True, default='', verbose_name='html generated by editor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_rep',
            field=models.TextField(blank=True, default='', verbose_name='json representation of lesson'),
        ),
    ]
