# Generated by Django 3.0.2 on 2020-01-19 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0006_auto_20200118_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='editor_html',
            new_name='html',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_rep',
        ),
    ]
