from django.db import models

from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField("personal description")

    def __str__(self):
        return "Profile for " + self.user.username

class Lesson(models.Model):
    title = models.CharField(max_length=300)
    slug = models.CharField(max_length=300)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    work_ahead = models.BooleanField(default=False)
    security = models.BooleanField(default=False)
    lesson_rep = models.TextField("json representation of lesson", default="", blank=True)
    editor_html = models.TextField("html generated by editor", default="", blank=True)
    active = models.BooleanField("is there currently an associated session", default=False)
    current_slide = models.IntegerField("what slide is the current session up to", default=-1)

    